#!/usr/bin/env bash

# template_variant: :ruby

if ! head -1 "$1" | grep -qE "^.{1,200}$"; then
  echo -e "\033[41mAborting commit. Your commit message is too long.\033[0m" >&2
  exit 1
fi
if ! head -1 "$1" | grep -qE "^(merge master)"; then
  exit 0
fi
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?!?: .{1,}$"; then
  echo -e "\033[41mWARNING: this commit does not follow conventional commit message guidelines\033[0m" >&2
fi
